# Generated by Django 2.0.5 on 2018-05-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0002_auto_20180512_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushel',
            name='amount_total',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='bushel',
            name='name_abbr',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bushel',
            name='name_plural',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bushel',
            name='name_short',
            field=models.CharField(blank=True, default='Food', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='amount_total',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='name_abbr',
            field=models.CharField(blank=True, default='gc', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='name_plural',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='name_short',
            field=models.CharField(blank=True, default='Money', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='amount_total',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='growth_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='name_abbr',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='name_plural',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='name_short',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='amount_total',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='growth_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='name_abbr',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='name_plural',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='name_short',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
