# Generated by Django 2.0.5 on 2018-05-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0003_auto_20180512_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushel',
            name='amount_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='amount_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='amount_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='growth_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rune',
            name='amount_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rune',
            name='growth_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
