# Generated by Django 2.0.5 on 2018-05-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0004_auto_20180512_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushel',
            name='name_abbr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bushel',
            name='name_plural',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bushel',
            name='name_short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='name_plural',
            field=models.CharField(blank=True, default='gcs', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='name_short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='name_abbr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='name_plural',
            field=models.CharField(blank=True, default='peasants', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='name_short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='name_abbr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='name_plural',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='name_short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
