# Generated by Django 2.0.5 on 2018-05-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0006_auto_20180512_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushel',
            name='name_abbr',
        ),
        migrations.RemoveField(
            model_name='bushel',
            name='name_plural',
        ),
        migrations.RemoveField(
            model_name='bushel',
            name='name_short',
        ),
        migrations.RemoveField(
            model_name='goldcoin',
            name='name_abbr',
        ),
        migrations.RemoveField(
            model_name='goldcoin',
            name='name_plural',
        ),
        migrations.RemoveField(
            model_name='goldcoin',
            name='name_short',
        ),
        migrations.RemoveField(
            model_name='peasant',
            name='name_abbr',
        ),
        migrations.RemoveField(
            model_name='peasant',
            name='name_plural',
        ),
        migrations.RemoveField(
            model_name='peasant',
            name='name_short',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='name_abbr',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='name_plural',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='name_short',
        ),
    ]
