# Generated by Django 2.0.5 on 2018-05-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0007_auto_20180512_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('island', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='kingdom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Kingdom'),
        ),
    ]
