# Generated by Django 2.0.5 on 2018-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0008_auto_20180512_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peasant',
            name='growth_rate',
            field=models.FloatField(default='10.0'),
        ),
    ]
