# Generated by Django 2.0.5 on 2018-05-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0010_auto_20180512_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushel',
            name='entity',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='defensivespecialist',
            name='entity',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='elite',
            name='entity',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='entity',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='offensivespecialist',
            name='entity',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='rune',
            name='entity',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='defensive_strength_value',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='entity',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='offensive_strength_value',
            field=models.IntegerField(default='1'),
        ),
    ]
