# Generated by Django 2.0.5 on 2018-05-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0012_auto_20180512_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushel',
            name='amount_total',
            field=models.IntegerField(default='10000'),
        ),
        migrations.AlterField(
            model_name='defensivespecialist',
            name='defensive_strength_value',
            field=models.IntegerField(default='4'),
        ),
        migrations.AlterField(
            model_name='elite',
            name='cost_currency',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='cost_currency', to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='amount_total',
            field=models.IntegerField(default='50000'),
        ),
        migrations.AlterField(
            model_name='offensivespecialist',
            name='offensive_strength_value',
            field=models.IntegerField(default='4'),
        ),
        migrations.AlterField(
            model_name='peasant',
            name='amount_total',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='consumes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumes', to='ntmeta.Entity'),
        ),
    ]
