# Generated by Django 2.0.5 on 2018-05-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0013_auto_20180512_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='military',
            name='province',
        ),
        migrations.AddField(
            model_name='military',
            name='attack_time',
            field=models.FloatField(default=20, verbose_name='Base attack time'),
        ),
        migrations.AddField(
            model_name='military',
            name='general_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='province',
            name='military',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Military'),
        ),
        migrations.AlterField(
            model_name='elite',
            name='cost_currency',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='cost_currency', to='ntmeta.Entity'),
        ),
    ]
