# Generated by Django 2.0.5 on 2018-05-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0014_auto_20180512_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='military',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Military'),
        ),
    ]
