# Generated by Django 2.0 on 2018-06-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0015_auto_20180512_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name_plural': 'Infrastructures',
            },
        ),
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mana', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Magic Models',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Human', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Races',
            },
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Science Models',
            },
        ),
        migrations.CreateModel(
            name='Thievery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name_plural': 'Infrastructures',
            },
        ),
        migrations.AlterModelOptions(
            name='military',
            options={'verbose_name_plural': 'Militaries'},
        ),
        migrations.AddField(
            model_name='province',
            name='infrastructure',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Infrastructure'),
        ),
        migrations.AddField(
            model_name='province',
            name='magic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Magic'),
        ),
        migrations.AddField(
            model_name='province',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Race'),
        ),
        migrations.AddField(
            model_name='province',
            name='science',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Science'),
        ),
        migrations.AddField(
            model_name='province',
            name='thievery',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Thievery'),
        ),
    ]
