# Generated by Django 2.0 on 2018-06-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0012_auto_20180601_0813'),
        ('ntgame', '0016_auto_20180601_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default='10', verbose_name='Total Number')),
                ('entity', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity')),
            ],
        ),
        migrations.RemoveField(
            model_name='bushel',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='bushel',
            name='province',
        ),
        migrations.RemoveField(
            model_name='goldcoin',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='goldcoin',
            name='province',
        ),
        migrations.RemoveField(
            model_name='peasant',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='peasant',
            name='growth_rate',
        ),
        migrations.RemoveField(
            model_name='peasant',
            name='province',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='rune',
            name='province',
        ),
        migrations.AddField(
            model_name='goldcoin',
            name='amount',
            field=models.IntegerField(default='50000', verbose_name='Total Number'),
        ),
        migrations.AddField(
            model_name='peasant',
            name='amount',
            field=models.IntegerField(default='1500', verbose_name='Total Number'),
        ),
        migrations.AddField(
            model_name='province',
            name='gold_coins',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.GoldCoin'),
        ),
        migrations.AddField(
            model_name='province',
            name='peasants',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Peasant'),
        ),
        migrations.AddField(
            model_name='province',
            name='runes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Rune'),
        ),
        migrations.AddField(
            model_name='rune',
            name='amount',
            field=models.IntegerField(default='0', verbose_name='Total Number'),
        ),
        migrations.AlterField(
            model_name='goldcoin',
            name='entity',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='rune',
            name='entity',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='rune',
            name='growth_rate',
            field=models.FloatField(blank=True, default='-5.0', null=True, verbose_name='How fast an Entity grows per turn'),
        ),
        migrations.DeleteModel(
            name='Bushel',
        ),
        migrations.AddField(
            model_name='province',
            name='food',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Food'),
        ),
    ]
