# Generated by Django 2.0 on 2018-06-01 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0018_auto_20180601_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Food'),
        ),
        migrations.AlterField(
            model_name='province',
            name='gold_coins',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ntgame.GoldCoin'),
        ),
        migrations.AlterField(
            model_name='province',
            name='peasants',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Peasant'),
        ),
        migrations.AlterField(
            model_name='province',
            name='runes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Rune'),
        ),
    ]
