# Generated by Django 2.0 on 2018-06-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0019_auto_20180601_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='military',
        ),
        migrations.AddField(
            model_name='military',
            name='province',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
    ]
