# Generated by Django 2.0 on 2018-06-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0020_auto_20180602_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensivespecialist',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='defensivespecialist',
            name='defensive_strength_value',
        ),
        migrations.RemoveField(
            model_name='defensivespecialist',
            name='military',
        ),
        migrations.RemoveField(
            model_name='elite',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='elite',
            name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='elite',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='elite',
            name='cost_scaling',
        ),
        migrations.RemoveField(
            model_name='elite',
            name='defensive_strength_value',
        ),
        migrations.RemoveField(
            model_name='elite',
            name='military',
        ),
        migrations.RemoveField(
            model_name='offensivespecialist',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='offensivespecialist',
            name='military',
        ),
        migrations.RemoveField(
            model_name='province',
            name='infrastructure',
        ),
        migrations.RemoveField(
            model_name='province',
            name='magic',
        ),
        migrations.RemoveField(
            model_name='province',
            name='science',
        ),
        migrations.RemoveField(
            model_name='province',
            name='thievery',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='consumes',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='defensive_strength_value',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='military',
        ),
        migrations.AddField(
            model_name='defensivespecialist',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Total Number'),
        ),
        migrations.AddField(
            model_name='defensivespecialist',
            name='defensive_stength_value',
            field=models.IntegerField(default=0, verbose_name='Defensive Power'),
        ),
        migrations.AddField(
            model_name='elite',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Total Number'),
        ),
        migrations.AddField(
            model_name='elite',
            name='defensive_stength_value',
            field=models.IntegerField(default=0, verbose_name='Defensive Power'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='province',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
        migrations.AddField(
            model_name='magic',
            name='province',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
        migrations.AddField(
            model_name='offensivespecialist',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Total Number'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Total Number'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='defensive_stength_value',
            field=models.IntegerField(default=0, verbose_name='Defensive Power'),
        ),
        migrations.AddField(
            model_name='thievery',
            name='province',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
        migrations.AlterField(
            model_name='defensivespecialist',
            name='entity',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='elite',
            name='entity',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='elite',
            name='offensive_strength_value',
            field=models.IntegerField(default=0, verbose_name='Offensive Power'),
        ),
        migrations.AlterField(
            model_name='offensivespecialist',
            name='offensive_strength_value',
            field=models.IntegerField(default=0, verbose_name='Offensive Power'),
        ),
        migrations.AlterField(
            model_name='province',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Race'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='entity',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='offensive_strength_value',
            field=models.IntegerField(default=0, verbose_name='Offensive Power'),
        ),
    ]
