# Generated by Django 2.0 on 2018-06-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0021_auto_20180603_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='military',
            name='defspec',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.DefensiveSpecialist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='military',
            name='elites',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Elite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='military',
            name='offspec',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.OffensiveSpecialist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='military',
            name='soldiers',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Soldier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='science',
            name='province',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
    ]
