# Generated by Django 2.0 on 2018-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0022_auto_20180603_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thievery',
            options={'verbose_name_plural': 'Thievery Models'},
        ),
        migrations.RemoveField(
            model_name='thievery',
            name='land',
        ),
        migrations.AddField(
            model_name='thievery',
            name='stealth',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='defensivespecialist',
            name='amount',
            field=models.IntegerField(default='0', verbose_name='Total Number'),
        ),
        migrations.AlterField(
            model_name='defensivespecialist',
            name='defensive_stength_value',
            field=models.IntegerField(default='4', verbose_name='Defensive Power'),
        ),
        migrations.AlterField(
            model_name='elite',
            name='amount',
            field=models.IntegerField(default='0', verbose_name='Total Number'),
        ),
        migrations.AlterField(
            model_name='elite',
            name='defensive_stength_value',
            field=models.IntegerField(default='4', verbose_name='Defensive Power'),
        ),
        migrations.AlterField(
            model_name='elite',
            name='offensive_strength_value',
            field=models.IntegerField(default='4', verbose_name='Offensive Power'),
        ),
        migrations.AlterField(
            model_name='offensivespecialist',
            name='amount',
            field=models.IntegerField(default='0', verbose_name='Total Number'),
        ),
        migrations.AlterField(
            model_name='offensivespecialist',
            name='offensive_strength_value',
            field=models.IntegerField(default='4', verbose_name='Offensive Power'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='amount',
            field=models.IntegerField(default='500', verbose_name='Total Number'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='defensive_stength_value',
            field=models.IntegerField(default='1', verbose_name='Defensive Power'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='offensive_strength_value',
            field=models.IntegerField(default='1', verbose_name='Offensive Power'),
        ),
    ]
