# Generated by Django 2.0 on 2018-06-03 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0012_auto_20180601_0813'),
        ('ntgame', '0023_auto_20180603_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Total Number')),
                ('effectiveness_value', models.FloatField(default=None, null=True, verbose_name="Entity's power multiplier")),
                ('entity', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Thief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Total Number')),
                ('entity', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity')),
            ],
        ),
    ]
