# Generated by Django 2.0 on 2018-06-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0024_mage_thief'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic',
            name='mages',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Mage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thievery',
            name='thieves',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Thief'),
            preserve_default=False,
        ),
    ]
