# Generated by Django 2.0.5 on 2018-05-11 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('data_type', models.CharField(choices=[(django.db.models.fields.CharField, 'Text'), (django.db.models.fields.IntegerField, 'Number'), (django.db.models.fields.FloatField, 'Float'), (django.db.models.fields.BooleanField, 'Bool'), (django.db.models.fields.related.ForeignKey, 'Entity')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Qualities',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='entity',
            field=models.ManyToManyField(to='ntmeta.Entity'),
        ),
        migrations.AddField(
            model_name='aspect',
            name='entity',
            field=models.ManyToManyField(to='ntmeta.Entity'),
        ),
        migrations.AddField(
            model_name='aspect',
            name='qualities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Quality'),
        ),
    ]
