# Generated by Django 2.0.5 on 2018-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='data_type',
            field=models.CharField(choices=[('type', 'Text'), ('type', 'Number'), ('type', 'Float'), ('type', 'Bool'), ('type', 'Entity')], max_length=20),
        ),
    ]
