# Generated by Django 2.0.5 on 2018-05-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0002_auto_20180511_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspect',
            name='entity',
            field=models.ManyToManyField(blank=True, to='ntmeta.Entity'),
        ),
        migrations.RemoveField(
            model_name='aspect',
            name='qualities',
        ),
        migrations.AddField(
            model_name='aspect',
            name='qualities',
            field=models.ManyToManyField(to='ntmeta.Quality'),
        ),
    ]
