# Generated by Django 2.0.5 on 2018-05-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0003_auto_20180511_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect',
            name='qualities',
        ),
        migrations.AddField(
            model_name='quality',
            name='aspect',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Aspect'),
        ),
    ]
