# Generated by Django 2.0.5 on 2018-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0004_auto_20180511_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='data_type',
            field=models.CharField(choices=[('CharField', 'Text'), ('IntegerField', 'Number'), ('FloatField', 'Float'), ('BooleanField', 'Bool'), ('ForeignKey', 'Entity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quality',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
