# Generated by Django 2.0.5 on 2018-05-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0005_auto_20180511_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspect',
            old_name='entity',
            new_name='entities',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='entity',
            new_name='assigned',
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
