# Generated by Django 2.0.5 on 2018-05-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0006_auto_20180511_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
