# Generated by Django 2.0 on 2018-06-01 08:13

from django.db import migrations, models
import ntmeta.choices


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0011_auto_20180512_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quality',
            name='description',
            field=models.CharField(default='No Description', max_length=255),
        ),
        migrations.AddField(
            model_name='quality',
            name='nullable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quality',
            name='data_type',
            field=models.CharField(choices=[('CharField', ntmeta.choices.QualityType('Text')), ('IntegerField', ntmeta.choices.QualityType('Number')), ('FloatField', ntmeta.choices.QualityType('Float')), ('BooleanField', ntmeta.choices.QualityType('Bool')), ('ForeignKey', ntmeta.choices.QualityType('Entity'))], max_length=20),
        ),
    ]
